export const FETCH_USERS_BEGIN = "FETCH_USERS_BEGIN";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE =  "FETCH_USERS_FAILURE";
export const ON_PAGE_CHANGED_ACTION =  "ON_PAGE_CHANGED_ACTION";

